; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = app3M_spiffs9M_fact512k_16MB.csv
lib_deps = 
	akj7/TM1637 Driver@^2.2.1
	cvmanjoo/RTC@^1.12.0
	bblanchon/ArduinoJson@^6.21.5
	tzapu/WiFiManager@^2.0.17
	https://github.com/Annabel369/ESP32FTPServer.git
upload_protocol = esptool
