; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
board_build.filesystem = littlefs
;board_build.partitions = app3M_spiffs9M_fact512k_16MB.csv
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
lib_deps = 
	akj7/TM1637 Driver@^2.2.1
	adafruit/RTClib@^2.1.4
	bblanchon/ArduinoJson@^6.21.5
	tzapu/WiFiManager@^2.0.17
	https://github.com/Annabel369/ESP32FTPServer.git
	esphome/ESP32-audioI2S@^2.3.0
;https://github.com/schreibfaul1/ESP32-audioI2S.git
upload_protocol = esptool
build_flags = 
	-DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

;	-mfix-esp32-psram-cache-issue
;	-DCONFIG_SPIRAM_USE
